name: Deploy

on: 
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: self-hosted
    steps:      
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }} 
        known_hosts: 'placeholder'
    - name: Adding Known Hosts
      run: ssh-keyscan -H ${{ secrets.SSH_SERVER_IP }} >> ~/.ssh/known_hosts
    - name: Deploy code
      working-directory: frontend
      run: rsync -avz . ${{ secrets.SSH_USER }}@${{ secrets.SSH_SERVER_IP }}:/tmp/build-${{ GITHUB_SHA }}/
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_SERVER_IP }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          echo "REACT_APP_TWITTER_BEARER_TOKEN=${{ secrets.REACT_APP_TWITTER_BEARER_TOKEN }}" >> /tmp/build-${{ GITHUB_SHA }}/.env
          echo "REACT_APP_DISCORD_URL=${{ secrets.REACT_APP_DISCORD_URL }}" >> /tmp/build-${{ GITHUB_SHA }}/.env
          echo "REACT_APP_GITHUB_TOKEN=${{ secrets.REACT_APP_GITHUB_TOKEN }}" >> /tmp/build-${{ GITHUB_SHA }}/.env
          cd /tmp/build-${{ GITHUB_SHA }}/
          docker build -t "tellorx-website:${{ GITHUB_SHA }}" /tmp/build-${{ GITHUB_SHA }}/
          docker kill $(docker ps -q)
          docker rm $(docker ps -a -q)
          docker run -p "3000:3000" -d "tellorx-website:${{ GITHUB_SHA }}"
          rm -rf /tmp/build-${{ GITHUB_SHA }}/